config/routes.rb
 Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, except: :destroy
  end
  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
  has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def show; end

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def edit; end

  def update
    @bookmark.update(bookmark_params)
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

# class ReviewsController < ApplicationController
#   def new
#     @review = Review.new(review_params)
#     @restaurant = Restaurant.find(params[:restaurant_id])
#     @review.restaurant = @restaurant
#   end

#   def create
#     @review = Review.new(review_params)
#     @restaurant = Restaurant.find(params[:restaurant_id])
#     @review.restaurant = @restaurant
#     if @review.save
#       redirect_to restaurant_path(@restaurant)
#     else
#       render :new
#     end
#   end

#   private

#   def review_params
#     params.require(:review).permit(:rating, :content)
#   end
# end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit; end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= render "navbar" %>
<div class="container col-6 col-offset-5 mt-5">
  <div>
    <h2 class="text-center m-3">Add movie</h2>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit 'Add to list', class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/bookmarks/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsVK8nYb9FK8IChYgWTOfhTDjeFt3Yfh6asw&usqp=CAU" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lists/new">New list</a>
      </li>
    </ul>
  </div>
</div>

app/views/bookmarks/edit.html.erb
<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/new.html.erb
<%= render "form", bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container col-6 col-offset-5 mt-5">
  <div>
    <h2 class="text-center m-3">New list</h2>
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/lists">
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsVK8nYb9FK8IChYgWTOfhTDjeFt3Yfh6asw&usqp=CAU" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/lists">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/lists/new">New list</a>
      </li>
    </ul>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "navbar" %>
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<%= render "navbar" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Hyades.jpg/1920px-Hyades.jpg);">
  <div class="container">
    <h1>Welcome to Listicon &#128253;</h1>
  </div>
</div>
<div class="cards">
  <% @lists.each do |list| %>
    <div class="card-category col" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <%= link_to list.name, list_path(list), class: "text-decoration-none text-center" %>
    </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render "navbar" %>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<%= render "navbar" %>
<div class="container">
<% if @list.photo.attached? %>
<div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key %>')">
<% else %>
<div class="card-category m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://picsum.photos/200/300')">
<% end %>
    <%= @list.name %>
  </div>
  <% bookmarks = @list.bookmarks %>
  <div class="cards">
    <% bookmarks.each do |bm| %>
      <div class="card-trip">
        <img src=<%= bm.movie.poster_url %> />
        <div class="card-trip-infos">
          <div>
            <h2><%= bm.movie.title %></h2>
            <p><%= bm.comment %></p>
          </div>
          <h2 class="card-trip-pricing"><%= link_to '🗑️', bookmark_path(bm), method: :delete, class: "text-decoration-none" %></h2>
        </div>
      </div>
    <% end %>
  <ul class="list-unstyled m-2">
    <li><%= link_to 'Rename this list' , edit_list_path(@list), class: "btn btn-primary m-3" %></li>
    <li><%= link_to 'Add movie' , new_list_bookmark_path(@list), class: "btn btn-success m-3" %></li>
    <li><%= link_to 'Delete this list' , list_path(@list), class: "btn btn-danger m-3", method: 'delete' %></li>
  </ul>
</div>